imports:
  - https://raw.githubusercontent.com/dotnet/crank/master/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  server:
    source:
      localFolder: ../
      project: ./src/MicroService.WebApi/MicroService.WebApi.csproj

scenarios:
  boroughBoundaries:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /api/v1/FeatureService/featurelookup?X=1006246&Y=174058&Key=BoroughBoundaries
        warmup: 2
        duration: 3
        connections: 2
        requests: 10

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010