repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: forbid-submodules

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]

      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        types: [yaml]
        files: ^\.github/workflows/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        exclude: ^(files/|docfx/articles/howto/|docfx/restapi/redoc\.standalone\.js|docker/grafana/provisioning/dashboards/)
