{
 "title": "Microsevices  API - Metrics",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environment", "query": "label_values(env)" },
   { "name": "application", "query": "label_values(app)" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "server", "label": "server", "query": "label_values(server)" },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Feature Lookup Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_feature_lookup_counter"
    }
   ]
  },
  {
   "title": "CPU Percentage Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_total_cpu_percentage_used{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "System Virtual Memory ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_virtual_memory{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "System Memory Working Set",
   "type": "gauge",
   "description": "Gets the associated process's physical memory usage, in bytes.",
   "gridPos": { "h": 4, "w": 6, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_memory_working_set{server=\"$server\"} "
    }
   ]
  },
  {
   "title": "CPU Percentage Used - User",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_user_cpu_percentage_used{server=\"$server\"}"
    }
   ]
  }
 ]
}