### YamlMime:ManagedReference
items:
- uid: MicroService.Common.Configuration.JaegerConfiguration
  commentId: T:MicroService.Common.Configuration.JaegerConfiguration
  id: JaegerConfiguration
  parent: MicroService.Common.Configuration
  children:
  - MicroService.Common.Configuration.JaegerConfiguration.AgentHost
  - MicroService.Common.Configuration.JaegerConfiguration.AgentPort
  - MicroService.Common.Configuration.JaegerConfiguration.Enabled
  - MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled
  - MicroService.Common.Configuration.JaegerConfiguration.ServiceName
  langs:
  - csharp
  - vb
  name: JaegerConfiguration
  nameWithType: JaegerConfiguration
  fullName: MicroService.Common.Configuration.JaegerConfiguration
  type: Class
  source:
    remote:
      path: src/MicroService.Common/Configuration/JaegerConfiguration.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: JaegerConfiguration
    path: ../src/MicroService.Common/Configuration/JaegerConfiguration.cs
    startLine: 2
  assemblies:
  - MicroService.Common
  namespace: MicroService.Common.Configuration
  syntax:
    content: public class JaegerConfiguration
    content.vb: Public Class JaegerConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - MicroService.Common.Configuration.JaegerConfiguration.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
- uid: MicroService.Common.Configuration.JaegerConfiguration.AgentHost
  commentId: P:MicroService.Common.Configuration.JaegerConfiguration.AgentHost
  id: AgentHost
  parent: MicroService.Common.Configuration.JaegerConfiguration
  langs:
  - csharp
  - vb
  name: AgentHost
  nameWithType: JaegerConfiguration.AgentHost
  fullName: MicroService.Common.Configuration.JaegerConfiguration.AgentHost
  type: Property
  source:
    remote:
      path: src/MicroService.Common/Configuration/JaegerConfiguration.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: AgentHost
    path: ../src/MicroService.Common/Configuration/JaegerConfiguration.cs
    startLine: 4
  assemblies:
  - MicroService.Common
  namespace: MicroService.Common.Configuration
  syntax:
    content: public string AgentHost { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property AgentHost As String
  overload: MicroService.Common.Configuration.JaegerConfiguration.AgentHost*
- uid: MicroService.Common.Configuration.JaegerConfiguration.ServiceName
  commentId: P:MicroService.Common.Configuration.JaegerConfiguration.ServiceName
  id: ServiceName
  parent: MicroService.Common.Configuration.JaegerConfiguration
  langs:
  - csharp
  - vb
  name: ServiceName
  nameWithType: JaegerConfiguration.ServiceName
  fullName: MicroService.Common.Configuration.JaegerConfiguration.ServiceName
  type: Property
  source:
    remote:
      path: src/MicroService.Common/Configuration/JaegerConfiguration.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: ServiceName
    path: ../src/MicroService.Common/Configuration/JaegerConfiguration.cs
    startLine: 6
  assemblies:
  - MicroService.Common
  namespace: MicroService.Common.Configuration
  syntax:
    content: public string ServiceName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ServiceName As String
  overload: MicroService.Common.Configuration.JaegerConfiguration.ServiceName*
- uid: MicroService.Common.Configuration.JaegerConfiguration.AgentPort
  commentId: P:MicroService.Common.Configuration.JaegerConfiguration.AgentPort
  id: AgentPort
  parent: MicroService.Common.Configuration.JaegerConfiguration
  langs:
  - csharp
  - vb
  name: AgentPort
  nameWithType: JaegerConfiguration.AgentPort
  fullName: MicroService.Common.Configuration.JaegerConfiguration.AgentPort
  type: Property
  source:
    remote:
      path: src/MicroService.Common/Configuration/JaegerConfiguration.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: AgentPort
    path: ../src/MicroService.Common/Configuration/JaegerConfiguration.cs
    startLine: 8
  assemblies:
  - MicroService.Common
  namespace: MicroService.Common.Configuration
  syntax:
    content: public int AgentPort { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property AgentPort As Integer
  overload: MicroService.Common.Configuration.JaegerConfiguration.AgentPort*
- uid: MicroService.Common.Configuration.JaegerConfiguration.Enabled
  commentId: P:MicroService.Common.Configuration.JaegerConfiguration.Enabled
  id: Enabled
  parent: MicroService.Common.Configuration.JaegerConfiguration
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: JaegerConfiguration.Enabled
  fullName: MicroService.Common.Configuration.JaegerConfiguration.Enabled
  type: Property
  source:
    remote:
      path: src/MicroService.Common/Configuration/JaegerConfiguration.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: Enabled
    path: ../src/MicroService.Common/Configuration/JaegerConfiguration.cs
    startLine: 10
  assemblies:
  - MicroService.Common
  namespace: MicroService.Common.Configuration
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: MicroService.Common.Configuration.JaegerConfiguration.Enabled*
- uid: MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled
  commentId: P:MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled
  id: RemoteAgentEnabled
  parent: MicroService.Common.Configuration.JaegerConfiguration
  langs:
  - csharp
  - vb
  name: RemoteAgentEnabled
  nameWithType: JaegerConfiguration.RemoteAgentEnabled
  fullName: MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled
  type: Property
  source:
    remote:
      path: src/MicroService.Common/Configuration/JaegerConfiguration.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: RemoteAgentEnabled
    path: ../src/MicroService.Common/Configuration/JaegerConfiguration.cs
    startLine: 12
  assemblies:
  - MicroService.Common
  namespace: MicroService.Common.Configuration
  syntax:
    content: public bool RemoteAgentEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property RemoteAgentEnabled As Boolean
  overload: MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled*
references:
- uid: MicroService.Common.Configuration
  commentId: N:MicroService.Common.Configuration
  name: MicroService.Common.Configuration
  nameWithType: MicroService.Common.Configuration
  fullName: MicroService.Common.Configuration
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Common
    name: Common
  - name: .
  - uid: MicroService.Common.Configuration
    name: Configuration
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Common
    name: Common
  - name: .
  - uid: MicroService.Common.Configuration
    name: Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
- uid: MicroService.Common.Configuration.JaegerConfiguration.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  parent: MicroService.Service.Helpers.ReflectionExtensions
  definition: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<JaegerConfiguration>(JaegerConfiguration)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<JaegerConfiguration>(JaegerConfiguration)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<MicroService.Common.Configuration.JaegerConfiguration>(MicroService.Common.Configuration.JaegerConfiguration)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of JaegerConfiguration)(JaegerConfiguration)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of MicroService.Common.Configuration.JaegerConfiguration)(MicroService.Common.Configuration.JaegerConfiguration)
  name.vb: ArePropertiesNotNull(Of JaegerConfiguration)(JaegerConfiguration)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.Common.Configuration.JaegerConfiguration)
    name: ArePropertiesNotNull
  - name: <
  - uid: MicroService.Common.Configuration.JaegerConfiguration
    name: JaegerConfiguration
  - name: '>'
  - name: (
  - uid: MicroService.Common.Configuration.JaegerConfiguration
    name: JaegerConfiguration
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.Common.Configuration.JaegerConfiguration)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - uid: MicroService.Common.Configuration.JaegerConfiguration
    name: JaegerConfiguration
  - name: )
  - name: (
  - uid: MicroService.Common.Configuration.JaegerConfiguration
    name: JaegerConfiguration
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<T>(T)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<T>(T)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<T>(T)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  name.vb: ArePropertiesNotNull(Of T)(T)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: MicroService.Service.Helpers.ReflectionExtensions
  commentId: T:MicroService.Service.Helpers.ReflectionExtensions
  parent: MicroService.Service.Helpers
  name: ReflectionExtensions
  nameWithType: ReflectionExtensions
  fullName: MicroService.Service.Helpers.ReflectionExtensions
- uid: MicroService.Service.Helpers
  commentId: N:MicroService.Service.Helpers
  name: MicroService.Service.Helpers
  nameWithType: MicroService.Service.Helpers
  fullName: MicroService.Service.Helpers
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
- uid: MicroService.Common.Configuration.JaegerConfiguration.AgentHost*
  commentId: Overload:MicroService.Common.Configuration.JaegerConfiguration.AgentHost
  name: AgentHost
  nameWithType: JaegerConfiguration.AgentHost
  fullName: MicroService.Common.Configuration.JaegerConfiguration.AgentHost
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MicroService.Common.Configuration.JaegerConfiguration.ServiceName*
  commentId: Overload:MicroService.Common.Configuration.JaegerConfiguration.ServiceName
  name: ServiceName
  nameWithType: JaegerConfiguration.ServiceName
  fullName: MicroService.Common.Configuration.JaegerConfiguration.ServiceName
- uid: MicroService.Common.Configuration.JaegerConfiguration.AgentPort*
  commentId: Overload:MicroService.Common.Configuration.JaegerConfiguration.AgentPort
  name: AgentPort
  nameWithType: JaegerConfiguration.AgentPort
  fullName: MicroService.Common.Configuration.JaegerConfiguration.AgentPort
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: MicroService.Common.Configuration.JaegerConfiguration.Enabled*
  commentId: Overload:MicroService.Common.Configuration.JaegerConfiguration.Enabled
  name: Enabled
  nameWithType: JaegerConfiguration.Enabled
  fullName: MicroService.Common.Configuration.JaegerConfiguration.Enabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled*
  commentId: Overload:MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled
  name: RemoteAgentEnabled
  nameWithType: JaegerConfiguration.RemoteAgentEnabled
  fullName: MicroService.Common.Configuration.JaegerConfiguration.RemoteAgentEnabled
