### YamlMime:ManagedReference
items:
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
  commentId: T:MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
  id: SwaggerFeatureRequestExamples
  parent: MicroService.WebApi.Extensions.Swagger
  children:
  - MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples
  langs:
  - csharp
  - vb
  name: SwaggerFeatureRequestExamples
  nameWithType: SwaggerFeatureRequestExamples
  fullName: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
  type: Class
  source:
    remote:
      path: src/MicroService.WebApi/Extensions/Swagger/SwaggerExamples.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: SwaggerFeatureRequestExamples
    path: ../src/MicroService.WebApi/Extensions/Swagger/SwaggerExamples.cs
    startLine: 8
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Extensions.Swagger
  summary: "\nSwagger Display Examples\n"
  example: []
  syntax:
    content: 'public class SwaggerFeatureRequestExamples : IExamplesProvider<FeatureAttributeLookupRequestModel>'
    content.vb: Public Class SwaggerFeatureRequestExamples Implements IExamplesProvider(Of FeatureAttributeLookupRequestModel)
  inheritance:
  - System.Object
  implements:
  - Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples
  commentId: M:MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples
  id: GetExamples
  parent: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
  langs:
  - csharp
  - vb
  name: GetExamples()
  nameWithType: SwaggerFeatureRequestExamples.GetExamples()
  fullName: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples()
  type: Method
  source:
    remote:
      path: src/MicroService.WebApi/Extensions/Swagger/SwaggerExamples.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: GetExamples
    path: ../src/MicroService.WebApi/Extensions/Swagger/SwaggerExamples.cs
    startLine: 14
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Extensions.Swagger
  summary: "\n\n"
  example: []
  syntax:
    content: public FeatureAttributeLookupRequestModel GetExamples()
    return:
      type: MicroService.WebApi.Models.FeatureAttributeLookupRequestModel
      description: ''
    content.vb: Public Function GetExamples() As FeatureAttributeLookupRequestModel
  overload: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples*
  implements:
  - Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}.GetExamples
references:
- uid: MicroService.WebApi.Extensions.Swagger
  commentId: N:MicroService.WebApi.Extensions.Swagger
  name: MicroService.WebApi.Extensions.Swagger
  nameWithType: MicroService.WebApi.Extensions.Swagger
  fullName: MicroService.WebApi.Extensions.Swagger
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Extensions
    name: Extensions
  - name: .
  - uid: MicroService.WebApi.Extensions.Swagger
    name: Swagger
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Extensions
    name: Extensions
  - name: .
  - uid: MicroService.WebApi.Extensions.Swagger
    name: Swagger
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}
  commentId: T:Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}
  parent: Swashbuckle.AspNetCore.Filters
  definition: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
  name: IExamplesProvider<FeatureAttributeLookupRequestModel>
  nameWithType: IExamplesProvider<FeatureAttributeLookupRequestModel>
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<MicroService.WebApi.Models.FeatureAttributeLookupRequestModel>
  nameWithType.vb: IExamplesProvider(Of FeatureAttributeLookupRequestModel)
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of MicroService.WebApi.Models.FeatureAttributeLookupRequestModel)
  name.vb: IExamplesProvider(Of FeatureAttributeLookupRequestModel)
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    isExternal: true
  - name: <
  - uid: MicroService.WebApi.Models.FeatureAttributeLookupRequestModel
    name: FeatureAttributeLookupRequestModel
  - name: '>'
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: MicroService.WebApi.Models.FeatureAttributeLookupRequestModel
    name: FeatureAttributeLookupRequestModel
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  parent: MicroService.Service.Helpers.ReflectionExtensions
  definition: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<SwaggerFeatureRequestExamples>(SwaggerFeatureRequestExamples)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<SwaggerFeatureRequestExamples>(SwaggerFeatureRequestExamples)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples>(MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of SwaggerFeatureRequestExamples)(SwaggerFeatureRequestExamples)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples)(MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples)
  name.vb: ArePropertiesNotNull(Of SwaggerFeatureRequestExamples)(SwaggerFeatureRequestExamples)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples)
    name: ArePropertiesNotNull
  - name: <
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
    name: SwaggerFeatureRequestExamples
  - name: '>'
  - name: (
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
    name: SwaggerFeatureRequestExamples
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
    name: SwaggerFeatureRequestExamples
  - name: )
  - name: (
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples
    name: SwaggerFeatureRequestExamples
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
  commentId: T:Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
  isExternal: true
  name: IExamplesProvider<T>
  nameWithType: IExamplesProvider<T>
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<T>
  nameWithType.vb: IExamplesProvider(Of T)
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of T)
  name.vb: IExamplesProvider(Of T)
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1
    name: IExamplesProvider
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Swashbuckle.AspNetCore.Filters
  commentId: N:Swashbuckle.AspNetCore.Filters
  isExternal: true
  name: Swashbuckle.AspNetCore.Filters
  nameWithType: Swashbuckle.AspNetCore.Filters
  fullName: Swashbuckle.AspNetCore.Filters
  spec.csharp:
  - uid: Swashbuckle
    name: Swashbuckle
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore
    name: AspNetCore
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore.Filters
    name: Filters
    isExternal: true
  spec.vb:
  - uid: Swashbuckle
    name: Swashbuckle
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore
    name: AspNetCore
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore.Filters
    name: Filters
    isExternal: true
- uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<T>(T)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<T>(T)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<T>(T)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  name.vb: ArePropertiesNotNull(Of T)(T)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: MicroService.Service.Helpers.ReflectionExtensions
  commentId: T:MicroService.Service.Helpers.ReflectionExtensions
  parent: MicroService.Service.Helpers
  name: ReflectionExtensions
  nameWithType: ReflectionExtensions
  fullName: MicroService.Service.Helpers.ReflectionExtensions
- uid: MicroService.Service.Helpers
  commentId: N:MicroService.Service.Helpers
  name: MicroService.Service.Helpers
  nameWithType: MicroService.Service.Helpers
  fullName: MicroService.Service.Helpers
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples*
  commentId: Overload:MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples
  name: GetExamples
  nameWithType: SwaggerFeatureRequestExamples.GetExamples
  fullName: MicroService.WebApi.Extensions.Swagger.SwaggerFeatureRequestExamples.GetExamples
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}.GetExamples
  commentId: M:Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}.GetExamples
  parent: Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}
  definition: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
  name: GetExamples()
  nameWithType: IExamplesProvider<FeatureAttributeLookupRequestModel>.GetExamples()
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<MicroService.WebApi.Models.FeatureAttributeLookupRequestModel>.GetExamples()
  nameWithType.vb: IExamplesProvider(Of FeatureAttributeLookupRequestModel).GetExamples()
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of MicroService.WebApi.Models.FeatureAttributeLookupRequestModel).GetExamples()
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}.GetExamples
    name: GetExamples
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider{MicroService.WebApi.Models.FeatureAttributeLookupRequestModel}.GetExamples
    name: GetExamples
    isExternal: true
  - name: (
  - name: )
- uid: MicroService.WebApi.Models.FeatureAttributeLookupRequestModel
  commentId: T:MicroService.WebApi.Models.FeatureAttributeLookupRequestModel
  parent: MicroService.WebApi.Models
  name: FeatureAttributeLookupRequestModel
  nameWithType: FeatureAttributeLookupRequestModel
  fullName: MicroService.WebApi.Models.FeatureAttributeLookupRequestModel
- uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
  commentId: M:Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
  isExternal: true
  name: GetExamples()
  nameWithType: IExamplesProvider<T>.GetExamples()
  fullName: Swashbuckle.AspNetCore.Filters.IExamplesProvider<T>.GetExamples()
  nameWithType.vb: IExamplesProvider(Of T).GetExamples()
  fullName.vb: Swashbuckle.AspNetCore.Filters.IExamplesProvider(Of T).GetExamples()
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
    name: GetExamples
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: Swashbuckle.AspNetCore.Filters.IExamplesProvider`1.GetExamples
    name: GetExamples
    isExternal: true
  - name: (
  - name: )
- uid: MicroService.WebApi.Models
  commentId: N:MicroService.WebApi.Models
  name: MicroService.WebApi.Models
  nameWithType: MicroService.WebApi.Models
  fullName: MicroService.WebApi.Models
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Models
    name: Models
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Models
    name: Models
