### YamlMime:ManagedReference
items:
- uid: MicroService.WebApi.Services.Cron.ScheduleConfig
  commentId: T:MicroService.WebApi.Services.Cron.ScheduleConfig
  id: ScheduleConfig
  parent: MicroService.WebApi.Services.Cron
  children:
  - MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression
  - MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo
  langs:
  - csharp
  - vb
  name: ScheduleConfig
  nameWithType: ScheduleConfig
  fullName: MicroService.WebApi.Services.Cron.ScheduleConfig
  type: Class
  source:
    remote:
      path: src/MicroService.WebApi/Services/Cron/ScheduleConfig.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: ScheduleConfig
    path: ../src/MicroService.WebApi/Services/Cron/ScheduleConfig.cs
    startLine: 21
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Services.Cron
  summary: "\n\n"
  example: []
  syntax:
    content: 'public class ScheduleConfig : IScheduleConfig'
    content.vb: Public Class ScheduleConfig Implements IScheduleConfig
  inheritance:
  - System.Object
  implements:
  - MicroService.WebApi.Services.Cron.IScheduleConfig
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - MicroService.WebApi.Services.Cron.ScheduleConfig.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
- uid: MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression
  commentId: P:MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression
  id: CronExpression
  parent: MicroService.WebApi.Services.Cron.ScheduleConfig
  langs:
  - csharp
  - vb
  name: CronExpression
  nameWithType: ScheduleConfig.CronExpression
  fullName: MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression
  type: Property
  source:
    remote:
      path: src/MicroService.WebApi/Services/Cron/ScheduleConfig.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: CronExpression
    path: ../src/MicroService.WebApi/Services/Cron/ScheduleConfig.cs
    startLine: 24
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Services.Cron
  summary: "\n\n"
  example: []
  syntax:
    content: public string? CronExpression { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property CronExpression As String
  overload: MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression*
  implements:
  - MicroService.WebApi.Services.Cron.IScheduleConfig.CronExpression
- uid: MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo
  commentId: P:MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo
  id: TimeZoneInfo
  parent: MicroService.WebApi.Services.Cron.ScheduleConfig
  langs:
  - csharp
  - vb
  name: TimeZoneInfo
  nameWithType: ScheduleConfig.TimeZoneInfo
  fullName: MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo
  type: Property
  source:
    remote:
      path: src/MicroService.WebApi/Services/Cron/ScheduleConfig.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: TimeZoneInfo
    path: ../src/MicroService.WebApi/Services/Cron/ScheduleConfig.cs
    startLine: 27
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Services.Cron
  summary: "\n\n"
  example: []
  syntax:
    content: public TimeZoneInfo? TimeZoneInfo { get; set; }
    parameters: []
    return:
      type: System.TimeZoneInfo
    content.vb: Public Property TimeZoneInfo As TimeZoneInfo
  overload: MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo*
  implements:
  - MicroService.WebApi.Services.Cron.IScheduleConfig.TimeZoneInfo
references:
- uid: MicroService.WebApi.Services.Cron
  commentId: N:MicroService.WebApi.Services.Cron
  name: MicroService.WebApi.Services.Cron
  nameWithType: MicroService.WebApi.Services.Cron
  fullName: MicroService.WebApi.Services.Cron
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Services
    name: Services
  - name: .
  - uid: MicroService.WebApi.Services.Cron
    name: Cron
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Services
    name: Services
  - name: .
  - uid: MicroService.WebApi.Services.Cron
    name: Cron
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MicroService.WebApi.Services.Cron.IScheduleConfig
  commentId: T:MicroService.WebApi.Services.Cron.IScheduleConfig
  parent: MicroService.WebApi.Services.Cron
  name: IScheduleConfig
  nameWithType: IScheduleConfig
  fullName: MicroService.WebApi.Services.Cron.IScheduleConfig
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
- uid: MicroService.WebApi.Services.Cron.ScheduleConfig.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  parent: MicroService.Service.Helpers.ReflectionExtensions
  definition: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<ScheduleConfig>(ScheduleConfig)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<ScheduleConfig>(ScheduleConfig)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<MicroService.WebApi.Services.Cron.ScheduleConfig>(MicroService.WebApi.Services.Cron.ScheduleConfig)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of ScheduleConfig)(ScheduleConfig)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of MicroService.WebApi.Services.Cron.ScheduleConfig)(MicroService.WebApi.Services.Cron.ScheduleConfig)
  name.vb: ArePropertiesNotNull(Of ScheduleConfig)(ScheduleConfig)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.WebApi.Services.Cron.ScheduleConfig)
    name: ArePropertiesNotNull
  - name: <
  - uid: MicroService.WebApi.Services.Cron.ScheduleConfig
    name: ScheduleConfig
  - name: '>'
  - name: (
  - uid: MicroService.WebApi.Services.Cron.ScheduleConfig
    name: ScheduleConfig
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.WebApi.Services.Cron.ScheduleConfig)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - uid: MicroService.WebApi.Services.Cron.ScheduleConfig
    name: ScheduleConfig
  - name: )
  - name: (
  - uid: MicroService.WebApi.Services.Cron.ScheduleConfig
    name: ScheduleConfig
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<T>(T)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<T>(T)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<T>(T)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  name.vb: ArePropertiesNotNull(Of T)(T)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: MicroService.Service.Helpers.ReflectionExtensions
  commentId: T:MicroService.Service.Helpers.ReflectionExtensions
  parent: MicroService.Service.Helpers
  name: ReflectionExtensions
  nameWithType: ReflectionExtensions
  fullName: MicroService.Service.Helpers.ReflectionExtensions
- uid: MicroService.Service.Helpers
  commentId: N:MicroService.Service.Helpers
  name: MicroService.Service.Helpers
  nameWithType: MicroService.Service.Helpers
  fullName: MicroService.Service.Helpers
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
- uid: MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression*
  commentId: Overload:MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression
  name: CronExpression
  nameWithType: ScheduleConfig.CronExpression
  fullName: MicroService.WebApi.Services.Cron.ScheduleConfig.CronExpression
- uid: MicroService.WebApi.Services.Cron.IScheduleConfig.CronExpression
  commentId: P:MicroService.WebApi.Services.Cron.IScheduleConfig.CronExpression
  parent: MicroService.WebApi.Services.Cron.IScheduleConfig
  name: CronExpression
  nameWithType: IScheduleConfig.CronExpression
  fullName: MicroService.WebApi.Services.Cron.IScheduleConfig.CronExpression
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo*
  commentId: Overload:MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo
  name: TimeZoneInfo
  nameWithType: ScheduleConfig.TimeZoneInfo
  fullName: MicroService.WebApi.Services.Cron.ScheduleConfig.TimeZoneInfo
- uid: MicroService.WebApi.Services.Cron.IScheduleConfig.TimeZoneInfo
  commentId: P:MicroService.WebApi.Services.Cron.IScheduleConfig.TimeZoneInfo
  parent: MicroService.WebApi.Services.Cron.IScheduleConfig
  name: TimeZoneInfo
  nameWithType: IScheduleConfig.TimeZoneInfo
  fullName: MicroService.WebApi.Services.Cron.IScheduleConfig.TimeZoneInfo
- uid: System.TimeZoneInfo
  commentId: T:System.TimeZoneInfo
  parent: System
  isExternal: true
  name: TimeZoneInfo
  nameWithType: TimeZoneInfo
  fullName: System.TimeZoneInfo
