### YamlMime:ManagedReference
items:
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
  commentId: T:MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
  id: SwaggerDocumentFilter
  parent: MicroService.WebApi.Extensions.Swagger
  children:
  - MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  langs:
  - csharp
  - vb
  name: SwaggerDocumentFilter
  nameWithType: SwaggerDocumentFilter
  fullName: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
  type: Class
  source:
    remote:
      path: src/MicroService.WebApi/Extensions/Swagger/SwaggerDocumentFilter.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: SwaggerDocumentFilter
    path: ../src/MicroService.WebApi/Extensions/Swagger/SwaggerDocumentFilter.cs
    startLine: 8
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Extensions.Swagger
  summary: "\n\n"
  example: []
  syntax:
    content: 'public class SwaggerDocumentFilter : IDocumentFilter'
    content.vb: Public Class SwaggerDocumentFilter Implements IDocumentFilter
  inheritance:
  - System.Object
  implements:
  - Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  commentId: M:MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  id: Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  parent: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
  langs:
  - csharp
  - vb
  name: Apply(OpenApiDocument, DocumentFilterContext)
  nameWithType: SwaggerDocumentFilter.Apply(OpenApiDocument, DocumentFilterContext)
  fullName: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument, Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  type: Method
  source:
    remote:
      path: src/MicroService.WebApi/Extensions/Swagger/SwaggerDocumentFilter.cs
      branch: develop
      repo: https://github.com/stuartshay/MicroService.git
    id: Apply
    path: ../src/MicroService.WebApi/Extensions/Swagger/SwaggerDocumentFilter.cs
    startLine: 11
  assemblies:
  - MicroService.WebApi
  namespace: MicroService.WebApi.Extensions.Swagger
  example: []
  syntax:
    content: public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    parameters:
    - id: swaggerDoc
      type: Microsoft.OpenApi.Models.OpenApiDocument
    - id: context
      type: Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext
    content.vb: Public Sub Apply(swaggerDoc As OpenApiDocument, context As DocumentFilterContext)
  overload: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply*
  implements:
  - Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
references:
- uid: MicroService.WebApi.Extensions.Swagger
  commentId: N:MicroService.WebApi.Extensions.Swagger
  name: MicroService.WebApi.Extensions.Swagger
  nameWithType: MicroService.WebApi.Extensions.Swagger
  fullName: MicroService.WebApi.Extensions.Swagger
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Extensions
    name: Extensions
  - name: .
  - uid: MicroService.WebApi.Extensions.Swagger
    name: Swagger
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.WebApi
    name: WebApi
  - name: .
  - uid: MicroService.WebApi.Extensions
    name: Extensions
  - name: .
  - uid: MicroService.WebApi.Extensions.Swagger
    name: Swagger
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter
  commentId: T:Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter
  parent: Swashbuckle.AspNetCore.SwaggerGen
  isExternal: true
  name: IDocumentFilter
  nameWithType: IDocumentFilter
  fullName: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
  - name: (
  - name: )
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  parent: MicroService.Service.Helpers.ReflectionExtensions
  definition: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<SwaggerDocumentFilter>(SwaggerDocumentFilter)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<SwaggerDocumentFilter>(SwaggerDocumentFilter)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter>(MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of SwaggerDocumentFilter)(SwaggerDocumentFilter)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter)(MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter)
  name.vb: ArePropertiesNotNull(Of SwaggerDocumentFilter)(SwaggerDocumentFilter)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter)
    name: ArePropertiesNotNull
  - name: <
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
    name: SwaggerDocumentFilter
  - name: '>'
  - name: (
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
    name: SwaggerDocumentFilter
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
    name: SwaggerDocumentFilter
  - name: )
  - name: (
  - uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter
    name: SwaggerDocumentFilter
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Swashbuckle.AspNetCore.SwaggerGen
  commentId: N:Swashbuckle.AspNetCore.SwaggerGen
  isExternal: true
  name: Swashbuckle.AspNetCore.SwaggerGen
  nameWithType: Swashbuckle.AspNetCore.SwaggerGen
  fullName: Swashbuckle.AspNetCore.SwaggerGen
  spec.csharp:
  - uid: Swashbuckle
    name: Swashbuckle
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore
    name: AspNetCore
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore.SwaggerGen
    name: SwaggerGen
    isExternal: true
  spec.vb:
  - uid: Swashbuckle
    name: Swashbuckle
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore
    name: AspNetCore
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore.SwaggerGen
    name: SwaggerGen
    isExternal: true
- uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  commentId: M:MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
  name: ArePropertiesNotNull<T>(T)
  nameWithType: ReflectionExtensions.ArePropertiesNotNull<T>(T)
  fullName: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull<T>(T)
  nameWithType.vb: ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  fullName.vb: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull(Of T)(T)
  name.vb: ArePropertiesNotNull(Of T)(T)
  spec.csharp:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: <
  - name: T
  - name: '>'
  - name: (
  - name: T
  - name: )
  spec.vb:
  - uid: MicroService.Service.Helpers.ReflectionExtensions.ArePropertiesNotNull``1(``0)
    name: ArePropertiesNotNull
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - name: T
  - name: )
- uid: MicroService.Service.Helpers.ReflectionExtensions
  commentId: T:MicroService.Service.Helpers.ReflectionExtensions
  parent: MicroService.Service.Helpers
  name: ReflectionExtensions
  nameWithType: ReflectionExtensions
  fullName: MicroService.Service.Helpers.ReflectionExtensions
- uid: MicroService.Service.Helpers
  commentId: N:MicroService.Service.Helpers
  name: MicroService.Service.Helpers
  nameWithType: MicroService.Service.Helpers
  fullName: MicroService.Service.Helpers
  spec.csharp:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
  spec.vb:
  - uid: MicroService
    name: MicroService
  - name: .
  - uid: MicroService.Service
    name: Service
  - name: .
  - uid: MicroService.Service.Helpers
    name: Helpers
- uid: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply*
  commentId: Overload:MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply
  name: Apply
  nameWithType: SwaggerDocumentFilter.Apply
  fullName: MicroService.WebApi.Extensions.Swagger.SwaggerDocumentFilter.Apply
- uid: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  commentId: M:Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  parent: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter
  isExternal: true
  name: Apply(OpenApiDocument, DocumentFilterContext)
  nameWithType: IDocumentFilter.Apply(OpenApiDocument, DocumentFilterContext)
  fullName: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument, Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
  spec.csharp:
  - uid: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
    name: Apply
    isExternal: true
  - name: (
  - uid: Microsoft.OpenApi.Models.OpenApiDocument
    name: OpenApiDocument
    isExternal: true
  - name: ','
  - name: " "
  - uid: Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext
    name: DocumentFilterContext
    isExternal: true
  - name: )
  spec.vb:
  - uid: Swashbuckle.AspNetCore.SwaggerGen.IDocumentFilter.Apply(Microsoft.OpenApi.Models.OpenApiDocument,Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext)
    name: Apply
    isExternal: true
  - name: (
  - uid: Microsoft.OpenApi.Models.OpenApiDocument
    name: OpenApiDocument
    isExternal: true
  - name: ','
  - name: " "
  - uid: Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext
    name: DocumentFilterContext
    isExternal: true
  - name: )
- uid: Microsoft.OpenApi.Models.OpenApiDocument
  commentId: T:Microsoft.OpenApi.Models.OpenApiDocument
  parent: Microsoft.OpenApi.Models
  isExternal: true
  name: OpenApiDocument
  nameWithType: OpenApiDocument
  fullName: Microsoft.OpenApi.Models.OpenApiDocument
- uid: Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext
  commentId: T:Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext
  parent: Swashbuckle.AspNetCore.SwaggerGen
  isExternal: true
  name: DocumentFilterContext
  nameWithType: DocumentFilterContext
  fullName: Swashbuckle.AspNetCore.SwaggerGen.DocumentFilterContext
- uid: Microsoft.OpenApi.Models
  commentId: N:Microsoft.OpenApi.Models
  isExternal: true
  name: Microsoft.OpenApi.Models
  nameWithType: Microsoft.OpenApi.Models
  fullName: Microsoft.OpenApi.Models
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.OpenApi
    name: OpenApi
    isExternal: true
  - name: .
  - uid: Microsoft.OpenApi.Models
    name: Models
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.OpenApi
    name: OpenApi
    isExternal: true
  - name: .
  - uid: Microsoft.OpenApi.Models
    name: Models
    isExternal: true
