version: '3.3'

networks:
  loki-network:

services:
  loki:
    container_name: 'loki'
    image: grafana/loki:2.7.3
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    #    volumes:
    #      - ./loki/loki-configuration.yaml:/etc/loki/local-config.yaml
    networks:
      - loki-network

  promtail:
    container_name: 'promtail'
    image: grafana/promtail:2.7.3
    volumes:
      - /var/log:/var/log
      #- ./loki/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network
