#!/usr/bin/env bash
set -ex

PGUSER=postgres psql <<- EOSQL
 CREATE TABLE public.test_data (
	id serial NOT NULL,
	"data" float8 NOT NULL,
	CONSTRAINT test_data_pkey PRIMARY KEY (id)
);
EOSQL

PGUSER=postgres psql <<- EOSQL
CREATE TABLE public.pluto (
	borough bpchar(2) NOT NULL,
	block int4 NULL,
	lot int2 NULL,
	cd int2 NULL,
	ct2010 bpchar(7) NULL,
	cg2010 bpchar(5) NULL,
	schooldist bpchar(2) NULL,
	council int2 NULL,
	zipcode bpchar(5) NULL,
	firecomp bpchar(4) NULL,
	policeprct int2 NULL,
	healthcenterdistrict int2 NULL,	
    healtharea int2 NULL,
	sanitboro int2 NULL,
	sanitdistrict int2 NULL,
	sanitsub bpchar(2) NULL,
	address varchar(100) NULL,
	zonedist1 bpchar(9) NULL,
	zonedist2 bpchar(9) NULL,
	zonedist3 bpchar(9) NULL,
	zonedist4 bpchar(9) NULL,
	overlay1 bpchar(4) NULL,
	overlay2 bpchar(4) NULL,
	spdist1	 bpchar(12) NULL,
	spdist2	 bpchar(12) NULL,
	spdist3	 bpchar(12) NULL,
	ltdheight bpchar(5) NULL,
	splitzone bpchar(1) NULL,
	bldgclass bpchar(2) NULL,
	landuse bpchar(2) NULL,
	easements int2 NULL,
	ownertype bpchar(1) NULL,
	ownername varchar(150) NULL,
	lotarea	int4 NULL,
	bldgarea int4 NULL,
	comarea int4 NULL,
	resarea	int4 NULL,
	officearea int4 NULL,
	retailarea int4 NULL,
	garagearea int4 NULL,
	strgearea int4 NULL,
	factryarea int4 NULL,
	otherarea int4 NULL,
	areasource bpchar(1) NULL,
	numbldgs int2 NULL,
	numfloors numeric(6,2) NULL,
	unitsres int2 NULL,
	unitstotal int2 NULL,
	lotfront numeric(7,2) NULL,
	lotdepth numeric(7,2) NULL,
	bldgfront numeric(7,2) NULL,
	bldgdepth numeric(7,2) NULL,
	ext	bpchar(2) NULL,
	proxcode bpchar(1) NULL,
	irrlotcode bpchar(1) NULL,
	lottype	 bpchar(1) NULL,
	bsmtcode bpchar(1) NULL,
	assessland numeric(13,2) NULL,
	assesstot numeric(13,2) NULL,
	exempttot numeric(13,2) NULL,
	yearbuilt int2 NULL,
	yearalter1 int2 NULL,
	yearalter2 int2 NULL,
	histdist varchar(100) NULL,
	landmark varchar(35) NULL,
	builtfar numeric(7,2) NULL,
	residfar numeric(7,2) NULL,
	commfar numeric(7,2) NULL,
	facilfar numeric(7,2) NULL,
	borocode int2 NULL,
	bbl numeric(12,2) NULL,
	condono int2 NULL,
	tract2010 bpchar(6) NULL,
	xcoord int4 NULL,
	ycoord int4 NULL,
	zonemap bpchar(3) NULL,
	zmcode bpchar(1) NULL,
	sanborn bpchar(8) NULL,
	taxmap bpchar(5) NULL,
	edesignum bpchar(5) NULL,
	appbbl numeric(12,2) NULL,
	appdate bpchar(10) NULL,
	plutomapid int2 NULL,
	firm07_flag	bpchar(1) NULL,
    pfirm15_flag bpchar(1) NULL,	
	version bpchar(6) NULL,
    dcpedited bpchar(3) NULL,	
	latitude numeric(9,6) NULL,
	longitude numeric(9,6) NULL,
    notes varchar(20) NULL
);
EOSQL

