node('docker') {

    stage('Git checkout') {
        git branch: 'develop', credentialsId: 'gihub-key', url: 'git@github.com:stuartshay/MicroService.git'
    }

    stage('Docker') {
        sh 'docker build -f docker/microservice-grafana.dockerfile/Dockerfile -t stuartshay/microservice-grafana:6.2.5-v3 ./docker/microservice-grafana.dockerfile'
        withDockerRegistry([credentialsId: 'docker-hub-navigatordatastore']) {
            sh 'docker push stuartshay/microservice-grafana:6.2.5-v3 '
        }
    }

    stage('Mail') {
        emailext attachLog: true, body: '', subject: "Jenkins build status - ${currentBuild.fullDisplayName}", to: 'sshay@yahoo.com'
    }

 }   
