node('master') {
    timestamps {
        String aws_credential_id = ""
        String aws_access_id = ""
        String aws_secret_key = ""

        stage('initialize') {
            def gitRepo = checkout scm
            // String git_url = gitRepo.GIT_URL
            git_branch = gitRepo.GIT_BRANCH.tokenize('/')[-1]
            String git_commit_id = gitRepo.GIT_COMMIT
            String git_short_commit_id = "${git_commit_id[0..6]}"


            String buildTime = sh(returnStdout: true, script: "date +'%Y.%V'").trim()
            currentBuild.displayName = (buildTime + "." + currentBuild.number + "." + git_branch + "." + git_short_commit_id)

            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'terraform_aws',
                    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                aws_access_id = USERNAME
                aws_secret_key = PASSWORD
            }
            if(!aws_access_id) {
                error("AWS access key is empty or not defined.")
            }
            if(!aws_secret_key) {
                error("AWS secret key is empty or not defined.")
            }
        }

        stage('tf-plan') {

        dir("postgres_rds_terraform") {


            wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: aws_secret_key, var: 'AWS_SECRET']]]) {
                sh """
                export AWS_ACCESS_KEY_ID=${aws_access_id}
                export AWS_SECRET_ACCESS_KEY=${aws_secret_key}
                terraform init
                terraform plan
               """
               }
            }

        }

        stage('tf-apply') {

        dir("postgres_rds_terraform") {
        if(Plan_Only.equalsIgnoreCase('true') | (Destroy_the_Environment.equalsIgnoreCase('true')) )  {
            println "Plan only run. Skipping Terraform apply."
        }
        else {
           input 'WARNING: Applying Terraform updates can result in unrecoverable destruction. Click "Proceed" to confirm Terraform update plan was reviewed and to authorize the updates to be applied, else click "Abort".'
           wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: aws_secret_key, var: 'AWS_SECRET']]]) {
               sh """
               export AWS_ACCESS_KEY_ID=${aws_access_id}
               export AWS_SECRET_ACCESS_KEY=${aws_secret_key}
               terraform apply -auto-approve
               """

                }

            }
            }

        }
        stage('tf-destroy') {

        dir("postgres_rds_terraform") {
        if(Destroy_the_Environment.equalsIgnoreCase('true')) {
        input 'WARNING: Applying Terraform destroy can result in unrecoverable destruction. Click "Proceed" to confirm Terraform update plan  to destroy was reviewed and to authorize the updates to be applied, else click "Abort".'
        wrap([$class: 'MaskPasswordsBuildWrapper', varPasswordPairs: [[password: aws_secret_key, var: 'AWS_SECRET']]]) {
            sh """
            export AWS_ACCESS_KEY_ID=${aws_access_id}
            export AWS_SECRET_ACCESS_KEY=${aws_secret_key}
            terraform destroy -force
            """
        }
        }
        else {

            println "Plan only run. Skipping Terraform apply."
                }

            }
            }

        }
    }
