name: Build/Test/Deploy
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: microservice-api
  REGION: us-east4
  ARTIFACT_REGISTRY_HOST: us-east4-docker.pkg.dev
  GCP_DOCKER_IMAGE: us-east4-docker.pkg.dev/velvety-byway-327718/microservice-api/microservice-api
  DH_DOCKER_IMAGE: stuartshay/microservice-api
  DOCKER_IMAGE_TAG: 5.1-buildx-${{ github.sha }}
  DOCKER_IMAGE_PLATFORM: linux/amd64,linux/arm/v7
  BUILD_NUMBER: ${{ github.sha }} 

on: 
  push:
   branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '5.0.x' ]

    steps:
      - name: Init
        uses: actions/checkout@v2

      - uses: rlespinasse/github-slug-action@v3.x

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.gcp_project }}
          service_account_key: ${{ secrets.GH_ACTIONS_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - run: gcloud info

      - uses: docker/setup-qemu-action@v1

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - run: echo ${{ steps.buildx.outputs.platforms }}

      - run: dotnet restore

      - name: Build
        run: |-
          docker build . -f docker/microservice-api-multi.dockerfile/Dockerfile  \
              --build-arg BUILD_NUMBER=${{env.BUILD_NUMBER}} \
              --tag ${{ env.DH_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG}} \
              --tag ${{ env.GCP_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG}}

      - name: Test
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: test/MicroService.Test
          report_name: MicroService.Test
          report_title: MicroService.Test
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_HOST }}

      - name: Package/Publish
        run: docker push ${{ env.GCP_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}-${{ env.GITHUB_REF_SLUG }}
          image:  ${{ env.GCP_DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}
          region: ${{ env.REGION }}
          flags: "--memory 1Gi --port 5000 --allow-unauthenticated"

      - name: Health Check
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ steps.deploy.outputs.url }}/health
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
